In [1]:
print([1,2,3])

[1, 2, 3]


In [1]:
import re

In [12]:
data_set = 'valid'

In [23]:
res = re.compile(rf'{data_set}_checkpoint([0-9]+)\.(.+)')

In [24]:
res

re.compile(r'valid_checkpoint([0-9]+)\.(.+)', re.UNICODE)

In [29]:
res.match('valid_checkpoint120.wiki.smatch').groups()

('120', 'wiki.smatch')

In [32]:
'wiki.smatch'.replace('.', '-')

'wiki-smatch'

In [33]:
a,b = zip(*[(1,3), (4,5)])

In [34]:
a

(1, 4)

In [37]:
len(a)

2

In [39]:
' '.join(map(str, a))

'1 4'

In [6]:
import os

for file in os.listdir('/dccstor/jzhou1/work/EXP/exp_debug'):
    print(file)

models_ep120_seed42
config_data_o5_no-mw_roberta-large-top24.sh


In [2]:
import re

a = re.compile('beam([0-9]+)')

In [42]:
a.match('beam100')

<_sre.SRE_Match object; span=(0, 7), match='beam100'>

In [183]:
a = re.compile(r'(.+)_checkpoint_(.+?)\.(.+)')

In [189]:
a.match('valid_checkpoint_last.wiki.smatch').groups()

('valid', 'last', 'wiki.smatch')

In [3]:
checkpoint_dir_re = re.compile(r'models_ep([0-9]+)_seed([0-9]+)')

In [5]:
checkpoint_dir_re.match('models_ep120_seed42').groups()

('120', '42')

In [7]:
a.setdefault('c', {})['valid'] = 3

In [6]:
import re
data_set='valid'
results_re = re.compile(rf'{data_set}_checkpoint([0-9]+)\.(.+)')
results_re.match('valid_checkpoint81.smatch').groups()

('81', 'smatch')

In [20]:
import glob

In [22]:
glob.glob('rm*')

['rm_certain_folders.sh']

In [13]:
sorted(['wiki-smatch_top3-avg', 'wiki-smatch_best1', 'wiki-smatch_top5-avg'])

['wiki-smatch_best1', 'wiki-smatch_top3-avg', 'wiki-smatch_top5-avg']

In [8]:
'smatch'.replace('.', '-')

'smatch'

In [16]:
!echo "smatch" | sed 's/\./-/g'

smatch


In [226]:
x = 79.99
c = 3
f'{x:.{c}f}'

'79.990'

In [229]:
'-' not in '---'

False

In [5]:
import os
os.path.lexists??

In [6]:
sorted??

In [1]:
a = [(1, [2]), (3, [4])]

In [4]:
[ep for ep, sc in a]

[1, 3]

In [1]:
action_path = '/dccstor/jzhou1/work/EXP/data-amr1/depfix_o5_no-mw_act-states/oracle/train.actions'

In [2]:
with open(action_path, 'r') as f:
    lines = [line.strip().split('\t') for line in f if line.strip]

In [3]:
len(lines)

10312

In [4]:
lens = [len(line) for line in lines]

In [5]:
min(lens)

3

In [6]:
max(lens)

515

In [7]:
lens.index(3)

1328

In [8]:
lines[1328]

['PRED("http://www.gao.gov/new.items/d10818.pdf")', 'SHIFT', 'SHIFT']

In [24]:
lens.index(4)

736

In [26]:
lines[736]

['COPY_LEMMA', 'SHIFT', 'LA(0,root)', 'SHIFT']

### encoding the graph structure

#### batching 

In [6]:
a = [0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1]
b = [0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0]
c = [0, 0, 0, 0, 1, 0, 0]

In [7]:
import torch

In [8]:
max_len = max([len(x) for x in (a, b, c)])

In [15]:
batch = torch.Tensor(3, max_len).fill_(0)

In [19]:
for i, x in enumerate([a, b, c]):
    batch[i, :len(x)] = torch.tensor(x)

In [20]:
batch

tensor([[0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 1., 0., 0.],
        [0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [29]:
batch_node = batch.clone()

In [30]:
batch_node[batch_node == 1] += 1

In [32]:
batch

tensor([[0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 1., 0., 0.],
        [0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [31]:
batch_node

tensor([[0., 0., 0., 2., 0., 0., 0., 0., 2., 2., 2., 0., 0.],
        [0., 2., 0., 0., 0., 2., 2., 0., 0., 2., 0., 0., 0.],
        [0., 0., 0., 0., 2., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [23]:
bb = torch.diag_embed(batch)

In [24]:
bb.view(-1, bb.size(-1))

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        

In [45]:
bb.view(-1, bb.size(-1))[batch.to(torch.bool).flatten()]

tensor([[0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [59]:
bb[batch.to(torch.bool)]

tensor([[0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [58]:
batch_node[batch.to(torch.bool)].long().unsqueeze(0)

tensor([[2, 2, 2, 2, 2, 2, 2, 2, 2]])

In [68]:
torch.gather(bb[batch.to(torch.bool)], dim=1, index=batch_node[batch.to(torch.bool)].long().unsqueeze(0).t())

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]])

In [70]:
batch_node[batch_node > 0].long()

tensor([2, 2, 2, 2, 2, 2, 2, 2, 2])

In [75]:
bb[batch.to(torch.bool)][torch.arange(9), batch_node[batch_node > 0].long()] = 3

In [92]:
bb.view(-1, bb.size(-1))[torch.nonzero(batch_node.flatten()).squeeze(), batch_node[batch_node > 0].long()] = 3

In [119]:
bb

tensor([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 3., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 3., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
         [0., 0., 3., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
         [0., 0., 3., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 1., 3., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,

In [120]:
torch.tril(bb)

tensor([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 3., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 3., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
         [0., 0., 3., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
         [0., 0., 3., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,

In [81]:
bb.view(-1, bb.size(-1))[batch.to(torch.bool).flatten()][0, 0]=10

In [89]:
torch.nonzero(batch_node.flatten()).size()

torch.Size([9, 1])

In [98]:
a = torch.zeros(10)
b = torch.zeros(5)
for x in [a, b]:
    x[-1] = 10
    print(x)

tensor([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.])
tensor([ 0.,  0.,  0.,  0., 10.])


In [99]:
print(a)

tensor([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.])


In [100]:
print(b)

tensor([ 0.,  0.,  0.,  0., 10.])


In [101]:
a

tensor([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.])

In [106]:
a[1:] = a[:-1]

RuntimeError: unsupported operation: some elements of the input tensor and the written-to tensor refer to a single memory location. Please clone() the tensor before performing the operation.

In [107]:
a.byte()

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=torch.uint8)

In [108]:
a = torch.zeros(14, 200, 256)

In [109]:
a[:, 0, :] = torch.ones(14, 256)

In [113]:
a[:, 0, :]

tensor([[1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        ...,
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.]])

In [114]:
b = a.view(14, 200 * 4, 256 // 4).transpose(0, 1)

In [118]:
b[:8]

tensor([[[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]],

        [[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]],

        [[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]],

        ...,

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0., 

In [121]:
a

tensor([[[1., 1., 1.,  ..., 1., 1., 1.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[1., 1., 1.,  ..., 1., 1., 1.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[1., 1., 1.,  ..., 1., 1., 1.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        ...,

        [[1., 1., 1.,  ..., 1., 1., 1.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0., 

In [125]:
def ss(a):
    a += 1
    return


In [126]:
ss(a)

In [127]:
a

tensor([[[2., 2., 2.,  ..., 2., 2., 2.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]],

        [[2., 2., 2.,  ..., 2., 2., 2.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]],

        [[2., 2., 2.,  ..., 2., 2., 2.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]],

        ...,

        [[2., 2., 2.,  ..., 2., 2., 2.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1., 

In [129]:
float('-inf')<0

True

In [134]:
torch.zeros_like(a.bool())

tensor([[[False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False],
         ...,
         [False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False]],

        [[False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False],
         ...,
         [False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False]],

        [[False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False],
         ...,
         [False, False, False,  ..., False, False, False],
         [

In [133]:
a

tensor([[[2., 2., 2.,  ..., 2., 2., 2.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]],

        [[2., 2., 2.,  ..., 2., 2., 2.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]],

        [[2., 2., 2.,  ..., 2., 2., 2.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]],

        ...,

        [[2., 2., 2.,  ..., 2., 2., 2.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1., 

In [8]:
import torch

In [16]:
list(range(torch.randint(0, 10, (100,)).max()))

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [33]:
a = torch.randint(1, 10, (2, 3, 3))

In [34]:
a

tensor([[[7, 3, 8],
         [4, 7, 3],
         [1, 4, 1]],

        [[3, 4, 6],
         [5, 1, 2],
         [3, 7, 1]]])

In [37]:
b = a.unsqueeze(1).repeat(1,2,1,1)

In [41]:
b[:, 1, :, :]

tensor([[[7, 3, 8],
         [4, 7, 3],
         [1, 4, 1]],

        [[3, 4, 6],
         [5, 1, 2],
         [3, 7, 1]]])

In [43]:
a.dim()

3

In [63]:
a.new([1,2,3])

tensor([1, 2, 3])

In [59]:
torch.cat([a.new(2, 0), a.new_ones(2, 3)], dim=1)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [62]:
torch.cat([a.new([]), a.new([1,2])], dim=0)

tensor([1, 2])