In [17]:
import torch

In [18]:
dir(torch.cuda)

['BoolStorage',
 'BoolTensor',
 'ByteStorage',
 'ByteTensor',
 'CharStorage',
 'CharTensor',
 'CudaError',
 'DeferredCudaCallError',
 'DoubleStorage',
 'DoubleTensor',
 'Event',
 'FloatStorage',
 'FloatTensor',
 'HalfStorage',
 'HalfTensor',
 'IntStorage',
 'IntTensor',
 'LongStorage',
 'LongTensor',
 'PIPE',
 'Popen',
 'ShortStorage',
 'ShortTensor',
 'Stream',
 '_CudaBase',
 '_StorageBase',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_after_fork',
 '_check_capability',
 '_check_driver',
 '_cudart',
 '_dummy_type',
 '_free_mutex',
 '_get_device_index',
 '_host_allocator',
 '_in_bad_fork',
 '_initialized',
 '_lazy_call',
 '_lazy_init',
 '_lazy_new',
 '_load_cudart',
 '_original_pid',
 '_queued_calls',
 '_register_after_fork',
 '_sleep',
 '_utils',
 'check_error',
 'comm',
 'contextlib',
 'ctypes',
 'cudaStatus',
 'cudart',
 'current_blas_handle',
 'current_device',
 'current_stream',
 'default_stream',

In [19]:
torch.cuda.is_available()

True

In [20]:
torch.cuda.device_count()

1

In [21]:
torch.cuda.get_device_name()

'Tesla K80'

In [23]:
torch.cuda.get_device_properties(0)

_CudaDeviceProperties(name='Tesla K80', major=3, minor=7, total_memory=11441MB, multi_processor_count=13)

In [27]:
!echo $HOSTNAME

dccxc261


In [28]:
!echo $CUDA_VISIBLE_DEVICES

6


In [29]:
!nvidia-smi

Thu Jun 25 10:24:31 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.39       Driver Version: 418.39       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           On   | 00000000:0F:00.0 Off |                    0 |
| N/A   23C    P8    27W / 149W |      0MiB / 11441MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K80           On   | 00000000:10:00.0 Off |                    0 |
| N/A   31C    P8    30W / 149W |      0MiB / 11441MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   2  T

6


dccxc261


In [14]:
import transition_amr_parser.data_oracle_o7 as do

In [15]:
do.main

<function transition_amr_parser.data_oracle_o7.main()>

In [4]:
a = f'123' \
    '456'

In [5]:
a

'123456'

In [6]:
a.copy()

AttributeError: 'str' object has no attribute 'copy'

In [1]:
a = [1,2,3]

In [2]:
a.remove(2)

In [3]:
a

[1, 3]

In [63]:
import functools

class dec:
    def __init__(self, outinstance, mode=True):
        self.mode = mode
        self.out = outinstance

    def __call__(self, f):
        @functools.wraps(f)
        def wrap_f(*args, **kwargs):
            v = f(*args, **kwargs)
            if self.mode:
                self.out.state.append(v)
            else:
                self.out.state.append(-1)
            return v
        return wrap_f


class a:
    
    def creat_dec(self, mode=False):
        return a.dec(self, mode)
    
#     class dec:
#         def __init__(self, outinstance, mode=True):
#             self.mode = mode
#             self.out = outinstance
        
#         def __call__(self, f):
#             @functools.wraps(f)
#             def wrap_f(*args, **kwargs):
#                 v = f(*args, **kwargs)
#                 if self.mode:
#                     self.out.state.append(v)
#                 else:
#                     self.out.state.append(-1)
#                 return v
#             return wrap_f
    
        
    def __init__(self, state=[1,2,3]):
        self.state = state
    

    
#     @dec(out=self.state)
    def ff(self, num):
        return num


In [53]:
a().dec().__class__

TypeError: __init__() missing 1 required positional argument: 'outinstance'

In [55]:
b = a()

In [66]:
b.ff(*None)

TypeError: ff() argument after * must be an iterable, not NoneType

In [1]:
import torch

In [2]:
a = torch.randn(4, 3)

In [6]:
b = torch.randint(2, (4,3), dtype=torch.uint8)

In [13]:
b

tensor([[1, 0, 0],
        [0, 1, 1],
        [0, 0, 0],
        [0, 0, 1]], dtype=torch.uint8)

In [14]:
a

tensor([[-0.9133,    -inf,    -inf],
        [   -inf,  0.0805,  0.1586],
        [   -inf,    -inf,    -inf],
        [   -inf,    -inf, -0.0330]])

In [21]:
a[b==0]=float('-Inf')

In [22]:
if b is not None:
    print(a)

tensor([[-0.9133,    -inf,    -inf],
        [   -inf,  0.0805,  0.1586],
        [   -inf,    -inf,    -inf],
        [   -inf,    -inf, -0.0330]])


In [7]:
b = torch.ones_like(a).fill_(-1)

In [23]:
b.new_zeros(2,3).byte()

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.uint8)

In [20]:
_[0, :2] = torch.tensor([1, 2])

In [26]:
b.argmax(dim=1)

tensor([2, 2, 2, 2])

In [27]:
a = torch.randn(4,3)

In [70]:
a

tensor([[12.3749,  1.2692,  1.9017],
        [-0.4581, -0.2810,  0.1315],
        [18.6107, -0.2688,  0.8802],
        [-1.4762,  0.1441, -1.8688]])

In [49]:
a[[0,2], 0] += torch.tensor([10, 20]).float()

In [72]:
a[~torch.ByteTensor([0,2,1,1])]

tensor([[12.3749,  1.2692,  1.9017],
        [-0.4581, -0.2810,  0.1315]])

In [66]:
a[:, [0,2]][torch.ByteTensor([0,0,1,1])] = a[:, [0,2]][torch.ByteTensor([0,0,1,1])] + 10

In [73]:
~torch.ByteTensor([0,2,1,1])

tensor([  1, 255,   0,   0], dtype=torch.uint8)

In [68]:
_

tensor([[12.3749,  1.2692,  1.9017],
        [-0.4581, -0.2810,  0.1315],
        [18.6107, -0.2688,  0.8802],
        [-1.4762,  0.1441, -1.8688]])

In [58]:
a[[0,1], [2,1]]

tensor([ 1.9017, -0.2810])

In [42]:
a.argmax(dim=1)

tensor([0, 2, 2, 1])

In [36]:
c, d = a.max(dim=1)

In [44]:
c

tensor([2.3749, 0.1315, 0.8802, 0.1441])

In [38]:
d

tensor([0, 2, 2, 1])

In [28]:
b = a.new_zeros(10,2, dtype=torch.byte)

AttributeError: module 'torch' has no attribute 'byte'

In [18]:
b.fill_(1)

tensor([[True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True]], dtype=torch.bool)

In [27]:
b.to(torch.uint8)

tensor([[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]], dtype=torch.uint8)

In [1]:
a = [1,2,3]

In [5]:
try:
    c = a.index(4)
except:
    print('aa')

aa


In [6]:
c

NameError: name 'c' is not defined

In [12]:
a[[0, 2, 1, 3]].resize_(3)

tensor([-0.0562,  0.9965,  1.4127])

In [16]:
b

tensor([ 0.7389,  0.9287,  0.8420, -0.5845])

In [1]:
import os

In [8]:
import torch

In [12]:
a = torch.randint(10, (5,))

In [13]:
a

tensor([5, 2, 8, 6, 0])

In [17]:
b = torch.randn(5, 10)

In [18]:
b

tensor([[ 1.9731,  1.2935, -0.8122,  0.7465, -0.4316, -0.3886, -0.0041, -0.5287,
          0.7888,  1.8620],
        [-1.0710, -0.3874, -2.7005,  0.2333, -0.8774,  0.2881,  0.3511, -0.1197,
         -1.7793,  0.2017],
        [ 0.4271,  0.9544,  0.1046, -0.8929, -0.8591, -0.7814,  1.2310, -1.2033,
         -1.6526, -1.5151],
        [-1.6580, -0.5108,  0.5466,  1.7875, -1.0071,  0.1220, -0.4841,  1.6868,
         -0.6112, -0.2859],
        [ 1.4411,  0.3097,  1.0023,  0.4942, -0.0370,  0.7113, -0.2221,  0.6855,
          1.5955, -0.2900]])

In [23]:
b[a.unsqueeze(-1)]

IndexError: index 5 is out of bounds for dimension 0 with size 5

In [24]:
a.unsqueeze(-1)

tensor([[5],
        [2],
        [8],
        [6],
        [0]])

In [28]:
c = b.gather(dim=-1, index=a.view(-1,1))

In [29]:
c

tensor([[-0.3886],
        [-2.7005],
        [-1.6526],
        [-0.4841],
        [ 1.4411]])

In [30]:
c[c>0] += 1

In [1]:
import torch

In [2]:
a = torch.tensor([[0,1,2,2,3], [0,0,1,2,1]])

In [3]:
a

tensor([[0, 1, 2, 2, 3],
        [0, 0, 1, 2, 1]])

In [80]:
src_pad_mask = torch.tensor([[0, 0, 0, 0], [1, 0, 0, 0]])

In [81]:
a = a + src_pad_mask.sum(dim=1).unsqueeze(1)

In [67]:
mask = torch.zeros(2, 5, 4)

In [68]:
tgt_idx = torch.arange(5).repeat(2, 1) + (torch.arange(2) * 5).view(-1, 1)

In [69]:
mask.view(-1, 4)[tgt_idx.view(-1), a.view(-1)] = 1

In [70]:
mask[1]

tensor([[0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [0., 0., 1., 0.]])

In [24]:
mask.to(tgt_idx)

tensor([[[1, 0, 0, 0],
         [0, 1, 0, 0],
         [0, 0, 1, 0],
         [0, 0, 1, 0],
         [0, 0, 0, 1]],

        [[1, 0, 0, 0],
         [1, 0, 0, 0],
         [0, 1, 0, 0],
         [0, 0, 1, 0],
         [0, 1, 0, 0]]])

In [28]:
!echo $CUDA_VISIBLE_DEVICES

3


In [33]:
a

tensor([[0, 1, 2, 2, 3],
        [0, 0, 1, 2, 1]])

In [38]:
b = a.clone()

In [39]:
b[b==-1]-=1

In [40]:
b

tensor([[-2,  1,  2,  2,  3],
        [-2, -2,  1,  2,  1]])

In [41]:
a

tensor([[-1,  1,  2,  2,  3],
        [-1, -1,  1,  2,  1]])

In [42]:
for x in range(0):
    print('a')

In [49]:
def bbb(aaa):
    aaa = aaa + 3
    return aaa

In [77]:
def ccc(aaa):
#     a = 3
    c = bbb(aaa)
    print(c)
    return aaa

In [78]:
ccc(torch.tensor([3]))

tensor([6])


tensor([3])

In [105]:
torch.zeros_like(a)

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]])

In [107]:
((_ == 0) == 1).sum(dim=0)

tensor([0, 0, 0, 0, 0])

In [90]:
_.sum(dim=1)

tensor([5, 5])

In [91]:
a

tensor([[0, 1, 2, 2, 3],
        [2, 2, 3, 4, 3]])

In [92]:
_

tensor([[0, 1, 2, 2, 3],
        [2, 2, 3, 4, 3]])

In [98]:
b = torch.tensor([2, 5])

In [99]:
a

tensor([[0, 1, 2, 2, 3],
        [2, 2, 3, 4, 3]])

In [101]:
b

tensor([2, 5])

In [102]:
a <= b.view(-1, 1) - 2

tensor([[1, 0, 0, 0, 0],
        [1, 1, 1, 0, 1]], dtype=torch.uint8)